ROR/config/routes.rb
Rails.application.routes.draw do
  root 'labs#index'
   get '/labs/new', to: 'labs#new', as:'new_lab'
   get '/labs/:id', to: 'labs#show', as: 'lab'
   post '/labs', to: 'labs#create'
   get '/labs/:id/edit' ,to: 'labs#edit' , as: 'edit_lab'
   put '/labs/:id' , to: 'labs#update'
   patch '/labs/:id' , to: 'labs#update'
   delete '/labs/:id', to: 'labs#destroy'
  get '/labs/:id/mark', to: 'labs#mark', as: 'mark_lab'
  post '/labs/:id/mark' , to: 'labs#grade'
  # resources :labs
end

ROR/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ROR/app/models/lab.rb
class Lab < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 500 }
   validates :grade, allow_nil: true, format: { with: /[A-F]/}
end

ROR/app/models/user.rb
class User < ApplicationRecord
  has_many :labs
  validates :first_name, presence: true, length: { maximum: 100 }
  validates :last_name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, length: { maximum: 150 }
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP

  def to_s
    email
  end
end

ROR/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ROR/app/controllers/labs_controller.rb
class LabsController < ApplicationController
  def index
    @labs=Lab.all
  end
  def show
    @lab=Lab.find(params[:id])
  end
  def new
    @lab=Lab.new
  end
  def create
    lab=Lab.new(params.require(:lab).permit(:title,:description))
    lab.user_id=1
    if lab.save
      redirect_to root_path
    else
      redirect_to root_path
      flash[:DANGER] = "Lab wasn't created! "
    end
  end
  def edit
    @lab=Lab.find(params[:id])
  end
  def update
    @lab=Lab.find(params[:id])
    @lab.update(params.require(:lab).permit(:title,:description))
    redirect_to root_url
  end
  def destroy
    @lab=Lab.find(params[:id])
    @lab.destroy
    redirect_to root_url
  end
  def mark
    @lab=Lab.find(params[:id])
  end
  def grade
    @lab=Lab.find(params[:id])
    if @lab.update(params.permit(:grade))
    redirect_to root_url
    else
      render :mark
      end
  end
end

ROR/app/helpers/application_helper.rb
module ApplicationHelper
end

ROR/app/helpers/labs_helper.rb
module LabsHelper
end

ROR/app/views/labs/edit.html.erb
<h1>Updating new lab</h1>
<%=form_with model: @lab do |f|  %>
  <%=f.text_field :title %>
  <%=f.text_area :description%>
  <%=f.submit%>
<%end %>

ROR/app/views/labs/index.html.erb
<h1>Labs</h1>
<% flash.each do |msg| %>

    <%= msg %>

<% end %>

<h1><%=link_to 'Create lab', new_lab_path %></h1>
<%@labs.each do |l| %>
  <h2>Title<br>
<%=l.title %></h2>
  <h2>Description</h2>
  <%=l.description %>
  <h2>Grade<br>
  <%=l.grade%></h2>
  <h2>Autor's email: <%=l.user%></h2>
  <%=link_to 'Show lab', lab_path(l) %>
  <%=link_to 'Grade lab', mark_lab_path(l) %>
  <%=link_to 'Edit lab', edit_lab_path(l) %>
  <%=link_to 'Delete lab', lab_path(l), method: :delete, data: {confirm: 'Are you sure?'} %>
<%end %>

ROR/app/views/labs/mark.html.erb
<h1>Grading lab</h1>
<%=form_with url: mark_lab_path(@lab) do |f|  %>
  <%=f.text_field :grade %>
  <%=f.submit%>
<%end %>

ROR/app/views/labs/new.html.erb
<h1>Creating new lab</h1>
<%=form_with model: @lab do |f|  %>
  <h2>Title</h2>
<%=f.text_field :title %>
  <h2>Description</h2>
<%=f.text_area :description%>
<%=f.submit%>
<%end %>

ROR/app/views/labs/show.html.erb
<h1><%=@lab.id %></h1>
<h1><%=@lab.title %></h1>
<h1><%=@lab.description%> </h1>
<h1><%=@lab.grade%> </h1>
<%=link_to 'Back', root_url %>

ROR/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kostya</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>